### ISSUE TITLE
LIM Issues

### ISSUE THREAD

**Issue by Zren** [Zren/material-decoration#1]
* [x] Format mnemonics
* [x] Figure out how to detect when `decoration->windowId` changes so I can update `AppMenuModel->winId` as KWin reuses the decorations I think. It will sometimes show the menu for Dolphin over top a SublimeText window.
* Refactor to use `QMenuBar` or implement:
	* [x] Switch submenu on Hover.
		* `DecoratedButton::hoverEnterEvent`
	* [x] Switch submenu on Left/Right Arrow.
		* https://github.com/psifidotos/applet-window-appmenu/blob/master/lib/appmenuapplet.cpp#L250
		* https://github.com/psifidotos/applet-window-appmenu/blob/master/lib/appmenuapplet.cpp#L287
	* [ ] Open Submenu on Shortcut.
		* SublimeText has mnemonics, and opens app submenus at the top left of the window (relative `(0,0)`). So I'll probably need to adjust the position during an `aboutToOpen` signal or something. Or update it's position during `updateButtonGeometry`.
		* The shortcut opens the LIM submenu instead of the Global Menu in Sublime Text, which is a good sign.
		* Decorations don't recieve KeyEvents afaik. So it's not possible to detect Alt pressed. I don't think it's possible to detect a menu shortcut either. Gtk menus open (in the wrong spot), but Qt menus don't at all.
			* https://github.com/KDE/kwin/blob/6abd23ed0220b14a4a05fa280869ba3c953565e3/input.cpp#L1076
	* [ ] Display mnemonics when holding `Alt`.
	* [x] Create an overflow menu when there isn't enough room for all menu items (Issue #10)
	* [x] Open menu on press instead of click.
* [x] Filter empty menu items without a label (Gtk apps 1st item).
* [x] Re-enable drawing the caption, using a gradient when covered by the appmenu.
* [ ] Fix all menu items disabled
	* ![2020-03-28___13-11-31](https://user-images.githubusercontent.com/416367/77829163-a2928b00-70f6-11ea-96df-52f89820cc14.png)
	* SublimeText > Preferences > Theme > Press `Esc` to close
	* This probably rebuilds the menu. The QActions inside the KDecoration buttons were probably deleted?
* [x] Window does not get focused when menu is clicked (Issue #3)
	* Note this affect the AppIcon and default AppMenu buttons too.
* [x] Fix invisible hitbox over the first menu item that triggers the menu overflow button.

### Features

* Hide menu on model windows.

**Comment by zzag** [comment]
> Figure out how to detect when decoration->windowId changes so I can update AppMenuModel->winId as KWin reuses the decorations I think

KWin does not reuse decorations. You probably need to update the app menu model when `DecorationClient::activeChanged` is emitted or something.

**Comment by Zren** [comment]
Hmmm, it seems I still had it bound to `DecoratedClient::captionChanged`. I haven't noticed it yet now that I'm using `DecoratedClient::hasApplicationMenuChanged`.

**Comment by nicman23** [comment]
#3 is working for me at least with the hover branch

**Comment by nicman23** [comment]
virt-manager with appmenu-gtk-module is non functional with lim. most entries are greyed out and i cannot switch from console to display. if you need a video or a log just tell what you want me to send you.

**Comment by nicman23** [comment]
hey can you please take a look at virt-manger?

**Comment by Zren** [comment]
Sorry @nicman23. I'd mostly ignored this issue since it I thought it only had the `Alt` feature. Gonna close this issue and break it into 2 new issues.
