### ISSUE TITLE
[Bug] Menu overflow

### ISSUE THREAD

**Issue by baduhai** [Zren/material-decoration#10]
It seems that there's already some sort of implementation for when the titlebar isn't long enough for the menu to be displayed, however the button available for the menu overflow is not clickable. See screenshot below for clearer explanation.

![Screenshot_20200421_140800](https://user-images.githubusercontent.com/31864305/79870119-617e5580-83da-11ea-9c00-66a95028e19b.png)

**Comment by Zren** [comment]
It's not yet checked in Issue #1. I haven't populated the menu yet, nor written the code for it to auto-open, when hovered.

**Comment by Zren** [comment]
Finished the overflow button.
