### ISSUE TITLE
Add a space between the menu and the caption

### ISSUE THREAD

**Issue by trmdi** [Zren/material-decoration#11]
Current:
![Screenshot_20200509_092300](https://user-images.githubusercontent.com/11857205/81461549-e2a95b00-91d6-11ea-8ee6-46289d2d9b24.png)

Expect:
![Screenshot_20200509_092506](https://user-images.githubusercontent.com/11857205/81461569-02408380-91d7-11ea-9707-187efbb4a99d.png)

When there is not enough space, the caption should be hidden or something like that, but there should be always a space between them.

**Comment by Zren** [comment]
I originally was planning to have a gradient fadeaway when the menu covered it, then I found outthe existing code can center the caption if not covered, or draw in the remaining space when the center position is overlapped.

I should probably get rid of the gradient, and center it in the remaining space. It already doesn't draw the caption when the menu is overflowing.

**Comment by trmdi** [comment]
Yes, but in some case centering it may be not enough e.g. when the remaining space == the caption's length.

**Comment by trmdi** [comment]
Maybe we should always center it in the whole length of the titlebar (not the remaining space) AND only show it if the space between the menu and the caption >= some minimum value ?

**Comment by trmdi** [comment]
A video about the behavior of LIM: https://youtu.be/nzFXRz-b3Ns?t=40

**Comment by ripefig** [comment]
Yeah, with the Unity implementaton all the problems go away.

**Comment by Zren** [comment]
Yep Unity's "drag even app buttons" is requested in Issue #2.

**Comment by Zren** [comment]
First I'll need to get rid of the `mousePressEvent` code that triggers `mouseReleaseEvent` (easy enough.

I don't think we can tell KDecoration to ignore the "press button", letting it fall through to the titlebar "move" unfortunately. There doesn't seem to be a "move" function anywhere in KDecoration either. So KWin is probably handling it.

There's a `mouseMoveEvent`, which I think is only triggered when a mouse button is pressed.

* https://github.com/KDE/kdecoration/blob/master/src/decorationbutton.h#L180
* https://github.com/KDE/kdecoration/blob/master/src/decoration.h#L228-L234

```
    virtual void hoverEnterEvent(QHoverEvent *event);
    virtual void hoverLeaveEvent(QHoverEvent *event);
    virtual void hoverMoveEvent(QHoverEvent *event);
    virtual void mouseMoveEvent(QMouseEvent *event);
    virtual void mousePressEvent(QMouseEvent *event);
    virtual void mouseReleaseEvent(QMouseEvent *event);
    virtual void wheelEvent(QWheelEvent *event);
```

We can use that with `mousePressEvent` to get the distrance dragged, and if it goes over the threshold to somehow trigger the "move window" event.

https://doc.qt.io/qt-5/qstylehints.html#startDragDistance-prop

Breeze has a "SizeGrip" in the bottom right which manually sends a `MoveResize` event to the xorg server. It sends `direction=4` or `_NET_WM_MOVERESIZE_SIZE_BOTTOMRIGHT`

* https://github.com/KDE/breeze/blob/master/kdecoration/breezesizegrip.cpp#L206
* https://github.com/KDE/breeze/blob/master/kdecoration/breezesizegrip.cpp#L283-L296
* https://specifications.freedesktop.org/wm-spec/latest/ar01s04.html#idm45766085227728

```
        clientMessageEvent.response_type = XCB_CLIENT_MESSAGE;
        clientMessageEvent.type = m_moveResizeAtom;
        clientMessageEvent.format = 32;
        clientMessageEvent.window = c->windowId();
        clientMessageEvent.data.data32[0] = rootPosition.x();
        clientMessageEvent.data.data32[1] = rootPosition.y();
        clientMessageEvent.data.data32[2] = 4; // bottom right
        clientMessageEvent.data.data32[3] = Qt::LeftButton;
        clientMessageEvent.data.data32[4] = 0;

        xcb_send_event( connection, false, QX11Info::appRootWindow(),
            XCB_EVENT_MASK_SUBSTRUCTURE_NOTIFY |
            XCB_EVENT_MASK_SUBSTRUCTURE_REDIRECT,
            reinterpret_cast<const char*>(&clientMessageEvent) );
```

We can probably try `_NET_WM_MOVERESIZE_MOVE` to send a Move only event. We can also look at what event the taskmanager widget sends when you right click a window > More Actions > Move.

```
#define _NET_WM_MOVERESIZE_MOVE              8   /* movement only */
```
