### ISSUE TITLE
Appmenu button's size is not consistent between windows

### ISSUE THREAD

**Issue by trmdi** [Zren/material-decoration#12]
![Screenshot_20200509_093659](https://user-images.githubusercontent.com/11857205/81461848-a70f9080-91d8-11ea-99a6-2663e7d690d3.png)

**Comment by Zren** [comment]
Duplicate of #9. Are you using the `master` branch?

**Comment by trmdi** [comment]
I'm using the latest commit 525cf3dbc87cd57cedebe41a74647b1cd80ebf45 on the `lim` branch.

**Comment by Zren** [comment]
`lim` was merged into `master`.

**Comment by trmdi** [comment]
Oh, didn't know that.
