### ISSUE TITLE
shadow is visible behind transparent window

### ISSUE THREAD

**Issue by mojtaba82** [Zren/material-decoration#20]
Shadow is visible under transparent window.

window with shadow set to none

![image](https://user-images.githubusercontent.com/4151722/89151844-19dd9d00-d577-11ea-8937-3db75c89ddf0.png)

window with shadow set to small

![image](https://user-images.githubusercontent.com/4151722/89151920-3aa5f280-d577-11ea-8e81-781225ba240e.png)

**Comment by Zren** [comment]
Yeah I've noticed this too. I'll need to compare zzag's code with to the default Breeze shadow code.

* https://github.com/Zren/material-decoration/blob/master/src/BoxShadowHelper.h
* https://github.com/Zren/material-decoration/blob/master/src/BoxShadowHelper.cc
* https://github.com/KDE/breeze/blob/master/libbreezecommon/breezeboxshadowrenderer.h
* https://github.com/KDE/breeze/blob/master/libbreezecommon/breezeboxshadowrenderer.cpp

**Comment by Zren** [comment]
Ooops. I accientally removed the mask applied to the shadows that makes the area under the window contents + titlebar transparent. Should be fixed now.

**Comment by mojtaba82** [comment]
Thanks a lot.
