### ISSUE TITLE
Close, maximize and minimize buttons are very small in gtk apps with CSDs since Plasma 5.20

### ISSUE THREAD

**Issue by mthw0** [Zren/material-decoration#22]
In Plasma 5.20, close, maximize, and minimize buttons now try to use the same look as buttons in SSDs resulting in very small buttons when your window decorations are used. Is this an issue on your side or is there something wrong on the Plasma side?
This is a screenshot from Firefox with CSDs enabled:

![Screenshot_20200918_083041](https://user-images.githubusercontent.com/31957530/93662684-4768a200-fa62-11ea-9dcb-71ed0c9624fe.png)

It looks the same in gtk3-demo. This issue was also reported on the KDE bug tracker: https://bugs.kde.org/show_bug.cgi?id=426670 Could you look into this?

**Comment by Zren** [comment]
I can reproduce in Gnome Chess. My Firefox has a `userChrome.css` that swapped the Breeze for Window's like buttons, so I'll test that later.

![2020-09-19___09-27-35](https://user-images.githubusercontent.com/416367/93668470-5ea39180-fa5a-11ea-8c19-00a1917a3106.png)

CSD should be controlled by the GTK theme. Atm I can't even find the "Gtk Theme" module in System Settings however. Or the Qt theme module (which should be the same module now). Weird.

**Comment by Zren** [comment]
Wow, neat. It appears changing Windows Decorations will now "paint" the decorations as `.svg` in `~/.config/gtk-3.0/assets/`. So cool!

**Comment by Zren** [comment]
It's drawing a 50x50 icon. However my icon is only 10x10.

**Comment by Zren** [comment]
I don't appear to scale the buttons in Qt apps. VeryLarge = 34px tall, Medium = 24px tall, Tiny = 20px tall.

Hmm, do I even scale the buttons for HiDPI?

**Comment by Zren** [comment]
If I scale the icon by `buttonRect.height() * 10/24`, I get:

* Tiny: 8x8 icon
* Small: 9x9 icon
* Medium: 10x10 icon
* Large: 12x12 icon
* Very Large: 14x14 icon

![2020-09-19___10-10-14](https://user-images.githubusercontent.com/416367/93669231-ad542a00-fa60-11ea-8ece-91a349c39e70.png)
![2020-09-19___10-09-53](https://user-images.githubusercontent.com/416367/93669234-ae855700-fa60-11ea-83b8-2e163a2fb407.png)
![2020-09-19___10-12-13](https://user-images.githubusercontent.com/416367/93669228-a9c0a300-fa60-11ea-91f6-be615b89208a.png)
![2020-09-19___10-10-51](https://user-images.githubusercontent.com/416367/93669230-ac22fd00-fa60-11ea-831e-9c6116ad80c9.png)
![2020-09-19___10-11-13](https://user-images.githubusercontent.com/416367/93669229-aaf1d000-fa60-11ea-9c45-22010f1cc0dc.png)

**Comment by Zren** [comment]
There's a cache of some sort I think. I added an extra line the maximize icon, but it was not reflected in the gtk assets.

![2020-09-19___10-34-06](https://user-images.githubusercontent.com/416367/93669659-b72b5c80-fa63-11ea-97da-d2d3c953dd64.png)

**Comment by Zren** [comment]
Looks like it renders to `/tmp/plasma-csd-generator/` first. It's empty though, so it's not cached.

* https://invent.kde.org/plasma/kde-gtk-config/-/merge_requests/2
* https://invent.kde.org/plasma/kde-gtk-config/-/merge_requests/2/diffs#72a005906f4c8e29bfd31f93b88d4591ff02fb0b_182_215

**Comment by Zren** [comment]
I needed to reboot for changes to take effect. So whatever process uses `kde-gtk-config` is loaded in needs to be restarted, just like I need to restart `kwin_x11` to test changes to the normal window decorations.

![2020-09-19___15-47-56](https://user-images.githubusercontent.com/416367/93687885-7f3a0e80-fa8f-11ea-9f0b-1b0801480aeb.png)

**Comment by Zren** [comment]
Had to also scale the line thickness. It's a bit blurry still since we're scaling the icon by `50/18 = 2.777` so it's a pain to get sharp lines for the minimize and maximize lines.

"Very Large" KWin buttons on top, with Chess Gtk CSD below:

![2020-09-19___21-29-34](https://user-images.githubusercontent.com/416367/93692283-3dc15780-fabf-11ea-9887-521997edbe6c.png)

**Comment by Zren** [comment]
In https://github.com/Zren/material-decoration/commit/65fe6f577a978a9e601241d29bea35185eb7f69c, I check if the process is `kded5`, and use a smaller padding around the icon. I can't easily get the button to use sharp lines, but at least the icons are visible now.

**Comment by mthw0** [comment]
It looks good now, thanks.
