### ISSUE TITLE
Option to move the window title position

### ISSUE THREAD

**Issue by CavaleriOmar** [Zren/material-decoration#23]
Beautiful product ... I've been looking for a way to have the "extended" global menu the title bar for a long time ... but, if it were possible, it would be interesting and practical to add two options related to the window title:
- the ability to move it near the window buttons (for example on the right, where I keep them, but also on the left);
- the ability to hide it completely.

**Comment by Zren** [comment]
Probably not going to add a show/hide titlebar option since breeze doesn't. I added the alignment code though.
