### ISSUE TITLE
Color variants

### ISSUE THREAD

**Issue by Madis0** [Zren/material-decoration#28]
E.g. white, black, blue, similar to [ChromeOS Plasma](https://store.kde.org/p/1354050).

**Comment by Zren** [comment]
It's controlled by your color theme. Edit a color theme and change the "titlebar" colors.

Or edit `~/.config/kdeglobals` directly:

```ini
[WM]
activeBackground=60,59,55
activeBlend=60,59,55
activeFont=Noto Sans,10,-1,5,50,0,0,0,0,0
activeForeground=255,255,255
frame=0,0,0
inactiveBackground=60,59,55
inactiveBlend=60,59,55
inactiveForeground=200,200,200
inactiveFrame=0,0,0
```

**Comment by Madis0** [comment]
For now I did indeed use a color scheme for it, but since the base is gray it always takes a higher saturation color to get the intended result.
