### ISSUE TITLE
@mojtaba82's fork (captionmenufeature branch)

### ISSUE THREAD

**Issue by Zren** [Zren/material-decoration#32]
> @mojtaba82: I fork this nice decoration. and add a branch named captionmenufeatcher and merge caption and menu like unity lim.
> It work but I'm not professional in programming. I would be glad if you test it.
> Thanks

* History: https://github.com/mojtaba82/material-decoration/commits/captionmenufeature
* Diff: https://github.com/mojtaba82/material-decoration/compare/04f6227315965bd428b6802c795d6e1f6f657a8c...captionmenufeature

Changes:

* LeftRight margins, with seperate values for maximized state.
  * I would layout it this way in the config:  
  > Normal:
  > Left Margin: `0px` Right Margin: `0px`
  > Maximized:
  > Left Margin: `0px` Right Margin: `0px`
  * However I wouldn't add the margin feature in the first place since it breaks fitt's law. Adding margins around the buttons means that the top left/right of the titlebar is no longer part of the button. I would add padding to the buttons instead. It seems like you take this into account with the "maximized margins" however I personally find the "shifting" in Firefox annoying when it goes maximized.
* Caption is always left aligned.
  * Makes sense you needed to add that, I haven't implemented Breeze's caption alignment mentioned in Issue #23.
* Hide caption when titlebar is hovered
  * You used a `} else /* ... multiple lines of code ... */ if (!titleBarIsHovered()) {` which is really hard to read...
  * You also used `if (!false) {} else {}` when it's much easier to read when reversing the if/else logic so it's `if (true) {} else {}`.
  * It's not animated, so I can't use it for Issue #16.

Note: I only read the code diff, I didn't actually compile and test it.

**Comment by mojtaba82** [comment]
Thank you for spend you'r time and give feedback.
Best wishes to you
