### ISSUE TITLE
Material-decoration does not show "roll up" button

### ISSUE THREAD

**Issue by Salvaju29ro** [Zren/material-decoration#36]
Hi, I have installed this decoration theme (very nice), but I noticed that the menu does not show the roll button, even though I have entered it in the settings.

I installed the menu via [AUR](https://aur.archlinux.org/packages/material-kwin-decoration-git/) on Arch Linux

[Here is](https://i.postimg.cc/ZYCfnVgs/Screenshot-06032021-120000.png) the photo of the "problem"

**Comment by Zren** [comment]
Ah, that's because I haven't gotten around to implementing the Shade or ContextHelp buttons since I don't use them. zzag only had Minimize, Maximize and Close implemented when I forked it.

* https://invent.kde.org/plasma/kdecoration/-/blob/master/src/decorationdefines.h#L19
* https://invent.kde.org/plasma/breeze/-/blob/master/kdecoration/breezebutton.cpp#L276
* https://invent.kde.org/plasma/breeze/-/blob/master/kdecoration/breezebutton.cpp#L93

**Comment by Zren** [comment]
Does this look okay?

![2021-03-06___11-08-14](https://user-images.githubusercontent.com/416367/110213025-45599a80-7e6c-11eb-82aa-531be08cc9cf.png)

**Comment by Salvaju29ro** [comment]
> Does this look okay?
> 
> ![2021-03-06___11-08-14](https://user-images.githubusercontent.com/416367/110213025-45599a80-7e6c-11eb-82aa-531be08cc9cf.png)

Yes, it looks nice

Thanks for the quick answer

**Comment by Zren** [comment]
Sorry, the ContextHelp icon took a little bit to modify from breeze as it has an arc and bezier curve in it.

![2021-03-06___13-19-40](https://user-images.githubusercontent.com/416367/110216707-a12d1f00-7e7e-11eb-9104-8ef71e67cf3a.png)

You should be able to used it now. Just pull the new commits, then reinstall.

https://github.com/Zren/material-decoration#building-from-source-1

**Comment by Salvaju29ro** [comment]
> Siamo spiacenti, l'icona ContextHelp ha richiesto un po 'di tempo per essere modificata poiché contiene un arco e una curva di bezier.
> 
> ![2021-03-06 ___ 13-19-40](https://user-images.githubusercontent.com/416367/110216707-a12d1f00-7e7e-11eb-9104-8ef71e67cf3a.png)
> 
> Dovresti essere in grado di usarlo ora. Basta tirare i nuovi commit, quindi reinstallarli.
> 
> https://github.com/Zren/material-decoration#building-from-source-1

It works ([photo](https://i.postimg.cc/Y9PvzNxx/Screenshot-06032021-194907.png)), thanks, I really appreciate it.
I think we can close it if that's okay for you
