### ISSUE TITLE
[Request] Make the window buttons svg

### ISSUE THREAD

**Issue by nicman23** [Zren/material-decoration#46]
it would be great to have an easy way to interchange window buttons and also to have the original as  svgs to use in  for example active window control plasmoid

**Comment by Zren** [comment]
See Issue #7. The widget already supports drawing the buttons in a widget like https://github.com/psifidotos/applet-window-appmenu.

The buttons are already rendered by the kde gtk config kded module into svgs (Issue #22) .

**Comment by nicman23** [comment]
thanks a lot :)
