### ISSUE TITLE
How to make Material Decoration default option for a global theme?

### ISSUE THREAD

**Issue by Unbuttun** [Zren/material-decoration#49]
So when I try to change the defaults of a `defaults` file inside look and theme folder of that theme and try to replace this part - 

```
[kwinrc][org.kde.kdecoration2]
BorderSize=None
ButtonsOnLeft=
ButtonsOnRight=IAX
library=org.kde.kwin.aurorae
theme=__aurorae__svg__Qogir-dark-circle
```
to something like this 

```
[kwinrc][org.kde.kdecoration2]
BorderSize=None
ButtonsOnLeft=
ButtonsOnRight=IAX
library=org.kde.kwin.aurorae
**theme=__aurorae__svg__Material**
```

It's not selecting the material decoration when I change the theme to the one above.

Any way to achieve it? thanks!!

**Comment by Zren** [comment]
Checkout `~/.config/kwinrc`. `theme=` shouldn't really matter, it's `library=` that loads the C++ plugin.

There's no guarantee that the user will have material-decoration installed.

https://github.com/Zren/material-decoration/blob/master/src/material.json#L5

```ini
[kwinrc][org.kde.kdecoration2]
library=com.github.zren.material
theme=Material
```

**Comment by Unbuttun** [comment]
Thanks, it's working now. I was trying to make a custom theme for my own usage, so that is the reason.

Also thanks for all the good things you did for KDE
