### ISSUE TITLE
Support for disabling blur

### ISSUE THREAD

**Issue by codic12** [Zren/material-decoration#5]
This option should be available both per application and for all apps (in my case I only don't want blur on certain applications' titlebar)

**Comment by Zren** [comment]
It's probably controlled by `src/material.json`

**Comment by gsbhasin123** [comment]
Yeah, I meant through the GUI :D

**Comment by baduhai** [comment]
By modifying lines 90 and 91 of [src/Decoration.cc](https://github.com/Zren/material-decoration/blob/f93937db40d873192b3d5cfbf22119cb0118c7fd/src/Decoration.cc#L90), I made it completely opaque.

**Comment by gsbhasin123** [comment]
Yup I know how to do that, but I meant with a gui (and also have a per app option) like many other decorations

**Comment by Zren** [comment]
I don't think we can dynamically toggle the blur.

* https://github.com/KDE/kwin/blob/master/decorations/decorationbridge.cpp#L226
* https://github.com/KDE/kwin/blob/master/decorations/decorationbridge.h
* https://github.com/KDE/kwin/blob/master/effects.cpp#L511
* https://github.com/KDE/kwin/blob/master/effects/blur/blur.cpp#L418

**Comment by codic12** [comment]
Hmm, oh well
