### ISSUE TITLE
menu items too close to each other need some space to breath

### ISSUE THREAD

**Issue by Aneeqasif** [Zren/material-decoration#52]
check out this [screenshot](https://i.imgur.com/0vgMTvn.png)

**Comment by Aneeqasif** [comment]
> This is asking to change the default, but it's basically a duplicate of Issue #19.

i am a noob user , its asking to edit a line can u please tell how to edit or which term should i add or remove in that line to have some space in between menu items

**Comment by Zren** [comment]
It's here: https://github.com/Zren/material-decoration/blob/master/src/Button.cc#L323

You can create a RGB color with: `= QColor(255, 255, 255);`

**Comment by Aneeqasif** [comment]
> It's here: https://github.com/Zren/material-decoration/blob/master/src/Button.cc#L323
> 
> You can create a RGB color with: `= QColor(255, 255, 255);` if you want a specific color.

` if (type() == KDecoration2::DecorationButtonType::Close) {
        auto *decoratedClient = deco->client().toStrongRef().data();
        const QColor hoveredColor  = QColor(255, 255, 255);
      
        QColor normalColor = QColor(hoveredColor);
        normalColor.setAlphaF(0);

        if (isPressed()) {
            const QColor pressedColor = decoratedClient->color(
                KDecoration2::ColorGroup::Warning,
                KDecoration2::ColorRole::Foreground
            ).lighter();
            return KColorUtils::mix(normalColor, pressedColor, m_transitionValue);
        }

        if (isHovered()) {
            return KColorUtils::mix(normalColor, hoveredColor, m_transitionValue);
        }
    }`

like this?
