### ISSUE TITLE
Doesn't compile on kUbuntu 20.04 (since commit #3f724dcf436233d24abe9f2dfc450ba5d0ac00dd)

### ISSUE THREAD

**Issue by Alt37** [Zren/material-decoration#57]
Tried on a clean Kubuntu 20.04 install
1) ticked "Source code" on "Software Sources" application (same as uncommenting "deb-src" lines on /etc/apt/sources.list) 
2)
```sudo apt dist-upgrade
sudo apt build-dep breeze
sudo apt build-dep kwin
sudo apt install git
``` 
3)
```
cd ~/Downloads
git clone https://github.com/Zren/material-decoration.git
cd material-decoration ; mkdir build ; cd build
```
4)
`cmake -DCMAKE_INSTALL_PREFIX=/usr ..`  
finishes with errors.

Just to make sure I started to browse though commit history and downloaded previous zip packages. The last package which builds properly on Ubuntu 20.04 is [ with commit #176c748524ac50865db988b9a6a7243f8da4e64f)](https://github.com/Zren/material-decoration/tree/176c748524ac50865db988b9a6a7243f8da4e64f) (("[Fix repainting the titlebar now that we have borders (Issue #41)](https://github.com/Zren/material-decoration/commit/176c748524ac50865db988b9a6a7243f8da4e64f)". 
[cmake_without_errors.txt](https://github.com/Zren/material-decoration/files/7467661/cmake_without_errors.txt)

With the next commit [#3f724dcf436233d24abe9f2dfc450ba5d0ac00dd](https://github.com/Zren/material-decoration/tree/3f724dcf436233d24abe9f2dfc450ba5d0ac00dd)) (("[Refactor X11 window code](https://github.com/Zren/material-decoration/commit/3f724dcf436233d24abe9f2dfc450ba5d0ac00dd)") I've got cmake errors.
[cmake_with_errors.txt](https://github.com/Zren/material-decoration/files/7467660/cmake_with_errors.txt)

With current KDE Neon User Edition latest "master" branch builds properly (it's not compatible with KWin 5.18.5 though).

**Comment by Zren** [comment]
Those 4 commits were sorta batched together. Try "Update plasma-workspace/libdbusmenuqt@f07b7f1"

* https://github.com/Zren/material-decoration/commit/0277a1d6e127bdaf89955ef18799e42cc07a6189#diff-c016b0ec9dab892f40704719dbdcd71c7ca7bf6ade9480903a13b59397a9552eL23

Not much changes besides:

```diff
diff --git a/src/libdbusmenuqt/CMakeLists.txt b/src/libdbusmenuqt/CMakeLists.txt
index 6ddc949..c8fd747 100644
--- a/src/libdbusmenuqt/CMakeLists.txt
+++ b/src/libdbusmenuqt/CMakeLists.txt
@@ -20,8 +20,8 @@ qt5_add_dbus_interface(libdbusmenu_SRCS com.canonical.dbusmenu.xml dbusmenu_inte
 
 add_library(dbusmenuqt STATIC ${libdbusmenu_SRCS})
 target_link_libraries(dbusmenuqt
-    Qt5::DBus
-    Qt5::Widgets
+    Qt::DBus
+    Qt::Widgets
 )
```

Does editing `src/libdbusmenuqt/CMakeLists.txt` and using `Qt5::DBus` work?

**Comment by Alt37** [comment]
@Zren 
Thanks!
I renamed both "Qt::DBus" and  "Qt::Widgets"  (also in "src/libdbusmenuqt/test/CMakeLists.txt") and now it builds properly. Patch bellow.

```
--- a/src/libdbusmenuqt/CMakeLists.txt
+++ b/src/libdbusmenuqt/CMakeLists.txt
@@ -20,8 +20,8 @@
 
 add_library(dbusmenuqt STATIC ${libdbusmenu_SRCS})
 target_link_libraries(dbusmenuqt
-    Qt::DBus
-    Qt::Widgets
+    Qt5::DBus
+    Qt5::Widgets
 )
 
 add_subdirectory(test)


--- a/src/libdbusmenuqt/test/CMakeLists.txt
+++ b/src/libdbusmenuqt/test/CMakeLists.txt
@@ -1,3 +1,3 @@
 add_executable(appmenutest main.cpp)
 target_link_libraries(appmenutest
-                        Qt::Widgets)
+                        Qt5::Widgets)
```

**Comment by Alt37** [comment]
Tested again. CMake still fails (for a different reason)
```
CMake Error at src/libdbusmenuqt/CMakeLists.txt:18 (qt_add_dbus_interface):
  Unknown CMake command "qt_add_dbus_interface".
```
According to [this](https://doc.qt.io/qt-5/qtdbus-cmake-qt-add-dbus-interface.html) page "qt_add_dbus_interface" was added in QT 5.15

@Zren 
If it's not trivial to target several QT version, maybe just create a separate branch for LTS distros with QT5.12?

**Comment by Zren** [comment]
Missed the `Qt::Widgets` in the tests `CMakeLists.txt`. Thanks @Alt37.

I also forgot how old Kubuntu's Qt version is. I've added a if/else switch to use the versionless macro when it detects Qt6.

*crosses fingers* should work now?

**Comment by Alt37** [comment]
I can confirm that now it compiles.
Thanks for your awesome projects & support @Zren !
